#!/bin/bash

module load jaspy
module load jasmin-sci



#===== EDIT HERE  =====#


var='cl' # CMIP6 variable name
tableID='Amon' # Amon, Omon, SImon etc...
model='HadGEM3-GC31-LL' # full model name
model_group='MOHC' # modelling group name


#==========================================================================================================#


src_dir=/badc/cmip6/data/CMIP6/CMIP/${model_group}/${model}/historical/

# find all ensemble versions (for looping)
ENS_PATHS=$(find $src_dir -type d -name "r*i1*" | cut -d / -f 1-10)

# create array of ensemble names
mapfile -t ENS_NAME_array < <( find $src_dir -type d -name "r*i1*" | cut -d / -f 10 )

# print arrays to console
#echo ${ENS_NAME_array[*]}

c=0

for i in $ENS_PATHS; do

        cd $src_dir/${ENS_NAME_array[c]}/${tableID}/${var}/gn/files/d*/
        echo $PWD

        save_dir=/gws/pw/j05/cop26_hackathons/bristol/project07/CMIP/historical/${var}/${model}/${ENS_NAME_array[c]}/

        if [ ! -d $save_dir ]; then
                mkdir -p $save_dir
        fi

        cp *.nc $save_dir

        c=$((c+1))
done
